- findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/service/FindBugsLauncher.java
- This allows plugins to specify other files such as bugrank.txt and adjustBugrank.txt
Without this, all detectors added by the tested plugin which have a base rank above 10 will be ignored, since the BugRank computation will always double the default score, making it impossible to test those with this library (which means everything except `SECURITY` and `CORRECTNESS`). You probably aren't seeing this, as all your plugin's category are `SECURITY`, which has a [rank of 5](https://code.google.com/p/findbugs/source/browse/findbugs/etc/bugrank.txt); which doubled is 10, and is still under the default threshold of 20.
If you changed the category of any pattern to anything else, such as `BAD_PRACTICE` you would notice the detector is never run, as it's filtered by the `ExecutionPlan`
> Copy all files in metadata folder

- plugin/src/main/java/com/h3xstream/findsecbugs/injection/AdditionalInjectionSource.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/sql/SqlInjectionDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/injection/sql/AdditionalInjectionSourceTest.java
- plugin/src/test/java/testcode/sqli/JavaSql.java
- plugin/src/test/resources/com/h3xstream/findsecbugs/injection/sql/SqlInjectionSource.properties
> Enable additional signatures to detector of injection

- plugin/src/main/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/main/resources/password-methods/password-methods-biginteger.txt
- plugin/src/main/resources/password-methods/password-methods-byte.txt
- plugin/src/main/resources/password-methods/password-methods-char.txt
- plugin/src/main/resources/password-methods/password-methods-string.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetectorTest.java
- plugin/src/test/java/testcode/password/ConstantPasswords.java
Detection of hard coded password in FindBugs works only for database passwords and detectors in FindSecurityBugs are very specific too. I have made quite complex detector for many different sinks having passwords or keys as input parameters of type String, char[], byte[] or BigInteger. Since I am not using real program flow analysis (for now), false positives are possible but quite rare (I have tested it using some existing code).
BTW: I had to made some changes (but I did not commit them) to be able to build the project - changing a line number in a test of XSS detection in JSP page to pass, copying of licence file to roots of modules and adding header to source code of 5 files from your last commit.
> Detector for hard coded passwords and cryptographic keys

- website/src/main/resources/license.htm
Nice website for find security bugs btw!
> website: corrected typos

- plugin/src/main/java/com/h3xstream/findsecbugs/injection/InjectionPoint.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/command/CommandInjectionSource.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/injection/command/CommandInjectionDetectorTest.java
- plugin/src/test/java/testcode/command/CommandInjection.java
Fixes #92. CWE identifiers should help tools parsing XML output with results of analysis.
> Added command injection sinks and CWE identifiers

- plugin/src/main/java/com/h3xstream/findsecbugs/injection/ldap/JndiLdapInjectionSource.java
- plugin/src/test/java/com/h3xstream/findsecbugs/injection/ldap/JndiLdapInjectionSourceAdditionalSignaturesTest.java
Added class constants, the test is switched on.
> Fixed incomplete candidate method for LDAP injections

- plugin/src/main/resources/metadata/messages.xml
Should be 'vulnerable _to_ injection'.
> Fix injection copy.

- plugin/src/main/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintAnalysis.java
- plugin/src/test/java/testcode/password/ConstantPasswords.java
> Fixed hard coded keys detector and out-of-bounds index in TaintAnalysis

- plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/InjectionSink.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/EngineRegistrar.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintAnalysis.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflow.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflowEngine.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrame.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintLocation.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummary.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummaryMap.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummaryMapLoader.java
- plugin/src/main/resources/taint-config/java-ee.txt
- plugin/src/main/resources/taint-config/java-lang.txt
- plugin/src/test/java/testcode/ResponseSplittingServlet.java
> Safe enums, dates, time and context path + javadoc

- plugin/src/main/java/com/h3xstream/findsecbugs/PredictableRandomDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/PredictableRandomDetectorTest.java
- plugin/src/test/java/testcode/InsecureRandom.java
Adding detection of ThreadLocalRandom, insecure random number generator since Java 7.
> Adding ThreadLocalRandom detection

- plugin/src/main/java/com/h3xstream/findsecbugs/cookie/PersistentCookieDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/cookie/PersistentCookieDetectorTest.java
- plugin/src/test/java/testcode/cookie/PersistentCookie.java
Proposed detector reports cookies set to expire in 1 year or more, like so:
`Cookie cookie = new Cookie("name", value);`
`cookie.setMaxAge(60*60*24*365);`
> Persistent cookie detector

- plugin/src/main/java/com/h3xstream/findsecbugs/android/GeolocationDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/CipherWithNoIntegrityDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/RsaNoPaddingDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/StaticIvDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/jsp/XslTransformJspDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/scala/XssMvcApiDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/serial/DeserializationGadgetDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/xml/XmlStreamReaderDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/xml/XxeDetector.java
- plugin/src/main/resources/taint-config/java-lang.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/crypto/CipherWithNoIntegrityDetectorTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/crypto/RsaNoPaddingDetectorTest.java
- plugin/src/test/java/testcode/crypto/CipherNoIntegrity.java
- plugin/src/test/java/testcode/crypto/RsaNoPadding.java
Fixes #270 and adds some tests. I've also added more safe classes for taint analysis and make some code cleaner (code quality of some detectors is still not very good).
> Bug fix of detection of bad cipher modes of operation and minor improvements

- plugin/pom.xml
The previous PR miss the version change to the pom.xml..
> Update JSP compiler

- README.md
Found using [mwic](http://jwilk.net/software/mwic).
> Remove duplicated word in README

- plugin-deps/src/main/java/org/apache/http/client/HttpClient.java
- plugin-deps/src/main/java/org/apache/http/impl/client/DefaultHttpClient.java
- plugin-deps/src/main/java/org/apache/http/impl/client/SystemDefaultHttpClient.java
- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/WeakTLSDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/crypto/WeakTLSDetectorTest.java
- plugin/src/test/java/testcode/crypto/WeakTLSProtocol.java
For issue #283, please kindly take a look.
> Implement detector for weak SSL/TLS protocols

- plugin-deps/src/main/java/com/fasterxml/jackson/annotation/JsonTypeInfo.java
- plugin-deps/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java
- plugin/pom.xml
- plugin/src/main/java/com/h3xstream/findsecbugs/serial/UnsafeJacksonDeserializationDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/serial/UnsafeJacksonDeserializationDetectorTest.java
- plugin/src/test/java/testcode/serial/JacksonSerialisationFalsePositive.java
- plugin/src/test/java/testcode/serial/UnsafeJacksonObjectDeserialization.java
- pom.xml
Signed-off-by: David Black <dblack@atlassian.com>
> Implement an unsafe jackson databind deserialization detector.

- plugin/pom.xml
- pom.xml
surefire-plugin and jetty-jspc plugin
> fixed out of date dependencies

- findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/BaseDetectorTest.java
- findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/EasyBugReporter.java
- findbugs-test-util/src/test/java/com/h3xstream/testng/VerboseTestListener.java
- plugin-deps/src/main/java/org/apache/commons/lang/StringEscapeUtils.java
- plugin-deps/src/main/java/org/apache/commons/lang3/StringEscapeUtils.java
- plugin-deps/src/main/java/org/apache/commons/text/StringEscapeUtils.java
- plugin/src/main/java/com/h3xstream/findsecbugs/HttpResponseSplittingDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/file/PathTraversalDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/crlf/CrlfLogInjectionDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/http/HttpParameterPollutionDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/scala/XssMvcApiDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/scala/XssTwirlDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
- plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssJspDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssServletDetector.java
- plugin/src/main/resources/safe-encoders/apache-commons.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/bugs/CoberturaCoverageTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/common/ByteCodeTraceTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/xss/encoder/ApacheCommonsLangTest.java
- plugin/src/test/java/testcode/xss/encoder/ApacheCommonsLang26.java
- plugin/src/test/java/testcode/xss/encoder/ApacheCommonsLang3.java
- plugin/src/test/java/testcode/xss/encoder/ApacheCommonsText.java
> Add coverage for Apache Commons Text API

- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintConfig.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodConfig.java
- plugin/src/main/resources/injection-sinks/path-traversal-in.txt
- plugin/src/main/resources/taint-config/java-net.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/file/PathTraversalDetectorTest.java
- plugin/src/test/java/testcode/pathtraversal/PathTraversal.java
Fix for #328.
In the second commit 7461999 I include the wrong definition in the exception output so that it's easy to find next time.
I also added createTempFile as Path Traversal sink and updated test. Hope that's right :)
Thanks.
> Fix java/io/File#createTempFile #328

- cli/build.gradle
- cli/findsecbugs.bat
- cli/findsecbugs.sh
This is a pretty small change.
I realized that the CLI was still using the Find Security Bugs 1.6.0 jar file.
I have updated the gradle build file and scripts.
> Updated the CLI to 1.7.1

- pom.xml
https://github.com/spotbugs/spotbugs/releases
> SpotBugs - 3.1.0-RC5

- plugin/src/main/resources/metadata/messages_ja.xml
- website/BuildWebPage.groovy
- website/templates/common_header.htm
I translated it into Japanese based on the latest version of messages.xml,
and fixed the language attribute value in bugs_ja.htm to "ja".
Tools:
- https://translate.google.co.jp/
- http://www.alc.co.jp/
- OmegaT (translation memory)
- Tomarigi (Japanese proofreading)
Reference:
https://vulncat.hpefod.com/
> Renew Japanese messages.

- plugin/src/test/java/com/h3xstream/findsecbugs/xss/JspXssDetectorTest.java
- website/BuildWebPage.groovy
- website/templates/bugs.htm
- website/templates/download.htm
- website/templates/security.htm
- Minor enhancement to the bugs page
- Update the version of the latest release (should have been committed before)
> Update the website template

- plugin-deps/src/main/java/javax/servlet/ServletOutputStream.java
- plugin/src/main/resources/injection-sinks/xss-servlet.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/xss/XssServletDetectorTest.java
- plugin/src/test/java/testcode/xss/servlets/XssServlet1.java
https://github.com/find-sec-bugs/find-sec-bugs/issues/341
mvn clean install is successful
@h3xstream - source formatting was changed when I cleaned the source prior to committing.  I did not see a default code formatter for the project, so applied the [sonar-developer](https://github.com/SonarSource/sonar-developer-toolset#code-style) formatting rules. 
I can reapply the changes to pristine source if desired.
> fix for: Identify XSS cause by ServletOutputStream.print() #341

- plugin/src/main/java/com/h3xstream/findsecbugs/PermissiveCORSDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/PermissiveCORSDetectorTest.java
- plugin/src/test/java/testcode/PermissiveCORS.java
> New implementation of CORS detector #313

- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/ErrorMessageExposureDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/crypto/ErrorMessageExposureDetectorTest.java
- plugin/src/test/java/testcode/crypto/ErrorMessages.java
I submit this pull request as I created issue #356
Followings are changes I made:
- Create a new detector ErrorMessageExposureDetector at crypto
- Create a test class ErrorMessageExposureDetectorTest with 2 test cases
- Update findbugs.xml and messages.xml correspondingly
Thank you
> Add ErrorMessageExposureDetector #356

- website/templates/download.htm
- website/templates/security.htm
- website/templates/tutorials.htm
Fixed a couple of typos, reworded a bit.
> Fixed typos in website

- plugin/src/main/java/com/h3xstream/findsecbugs/crypto/InsufficientKeySizeRsaDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/crypto/InsufficientKeySizeRsaDetectorTest.java
- plugin/src/test/java/testcode/crypto/InsufficientKeySizeRsa.java
Detect weak keysize when multiple args are passed to KeyPairGenerator.getInstance
> Improve RSA weak keysize detection

- plugin/src/main/java/com/h3xstream/findsecbugs/xml/XmlStreamReaderDetector.java
- plugin/src/main/java/com/h3xstream/findsecbugs/xml/XxeDetector.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/xml/XmlStreamReaderDetectorTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/xml/XxeDetectorXPathExpressionTest.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/FilteredReaderSafe.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/FilteredReaderVulnerable.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/XMLEventReaderSafe.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/XMLEventReaderVulnerable.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/XMLStreamReaderSafe.java
- plugin/src/test/java/testcode/xxe/xmlinputfactory/XMLStreamReaderVulnerable.java
- plugin/src/test/java/testcode/xxe/xpathexpression/XPathExpressionSafe.java
- plugin/src/test/java/testcode/xxe/xpathexpression/XPathExpressionVulnerable.java
Increase the coverage **javax/xml/stream/XMLInputFactory**
Method:
- createXMLStreamReader (Already present)
- createXMLEventReader (New)
- createFilteredReader (New)
> Add detectors for more XXE coverage #138

- plugin/src/main/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetectorTest.java
- plugin/src/test/java/testcode/xxe/transformerfactory/SaxTransformerFactoryVulnerable.java
TransformerFactory was already covered but not SAXTransformerFactory #138
>  Added support for SAXTransformerFactory

- plugin/src/test/java/com/h3xstream/findsecbugs/injection/crlf/CrlfLogInjectionDetectorTest.java
- plugin/src/test/java/testcode/logging/Slf4jSample.java
> Testcases for SLF4J

- cli/findsecbugs.sh
It seems that the change was made to the .bat file but not to the .sh file.
> Update to use findsecbugs-plugin 1.8.0

- plugin/src/main/java/com/h3xstream/findsecbugs/PredictableRandomDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/PredictableRandomDetectorTest.java
- plugin/src/test/java/testcode/InsecureRandom.java
#243 
Was too busy for a long time, but now finally did improvements, discussed in the first pull request.
https://github.com/find-sec-bugs/find-sec-bugs/pull/437
> Extended PredictiveRandomDetector (added new test)

- plugin/src/main/java/com/h3xstream/findsecbugs/PredictableRandomDetector.java
- plugin/src/test/java/com/h3xstream/findsecbugs/PredictableRandomDetectorTest.java
- plugin/src/test/java/testcode/InsecureRandom.java
#243 
Added checks for using packages from this issue into existing detector
This is my first pull request to this project, thus it may be some style and dependencies mistakes.
> Extended PredictiveRandomDetector

- plugin/src/main/resources/metadata/messages.xml
> Improve XSLT RCE resolution

- findsecbugs-test-kotlin/src/test/kotlin/com/h3xstream/findsecbugs/injection/Logging.kt
- findsecbugs-test-kotlin/src/test/kotlin/com/h3xstream/findsecbugs/injection/Slf4jSample.kt
- plugin-deps/src/main/java/org/slf4j/Logger.java
- plugin/src/main/java/com/h3xstream/findsecbugs/injection/InjectionSink.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
- plugin/src/main/resources/taint-config/java-lang.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/injection/crlf/CrlfLogInjectionDetectorTest.java
- plugin/src/test/java/testcode/logging/Slf4jSample.java
- pom.xml
The changes I have made were specifically to address CRLF detector issues. However, they will also be applied to all other Injection Detectors since they share the same code.
> Added Kotlin support for CRLF detector

- plugin/src/main/resources/taint-config/java-lang.txt
- plugin/src/test/java/com/h3xstream/findsecbugs/kotlin/IdentityFunctionCommandInjectionTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/kotlin/KotlinCommandInjectionDetectorTest.java
- plugin/src/test/java/com/h3xstream/findsecbugs/kotlin/StringManipulationCommandInjectionTest.java
> Fix Kotlin handling of the String being build with the Appendable class

- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/extra/JstlExpressionWhiteLister.java
- plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/extra/PotentialValueTracker.java
- plugin/src/main/resources/metadata/findbugs.xml
- plugin/src/main/resources/metadata/messages.xml
- plugin/src/test/java/com/h3xstream/findsecbugs/jsp/JstlExpressionWhiteListerTest.java
- plugin/src/test/webapp/jstl/jstl_expression_insecure.jsp
- plugin/src/test/webapp/jstl/jstl_expression_secure.jsp
This change is addressing the following issue: #399 #404 #353
It does not provide a perfect solution to remove all XSS false positive in JSP but it will cover some recurrent cases.
> JSTL expression white listing

- findsecbugs-plugin/pom.xml
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/script/SpelViewDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ldap/LdapEntryPoisoningDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/scala/PlayUnvalidatedRedirectDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/scala/SslDisablerDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/xml/XxeDetector.java
- findsecbugs-samples-java/src/test/java/testcode/HttpParameterPollution.java
- findsecbugs-samples-java/src/test/java/testcode/crypto/WeakMessageDigest.java
- findsecbugs-samples-jsp/pom.xml
- pom.xml
Some code refactoring needed for OpcodeStackDetector related to SpotBugs update.
Document some deprecated API used in samples.
> Update SpotBugs dependency + others deps

- findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/BaseDetectorTest.java
- findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/service/FindBugsLauncher.java
https://github.com/find-sec-bugs/find-sec-bugs/issues/479
> Add configurable metadataFolder in FindBugsLauncher

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
Simple typo fix, correct red to read.
> Fix typo in HTTPONLY_COOKIE description

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
This should fix "Error: missing bug code for key SECEMA"
> Fix key misspell #526

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
Links update.
- Many deprecated link were update.
- http to https when possible
- Fix description for Pebble injection
> Fix links in the messages

- .travis.yml
- cli/README.md
- cli/build.gradle
- cli/findsecbugs.bat
- cli/gradle.properties
Build script used to package 1.10.1
> Introduce a properties file to avoid repeating the versions

- findsecbugs-plugin/src/main/resources/metadata/messages_ja.xml
> Update Japanese messages

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
- findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/StaticContextTaintPropagationTest.java
- findsecbugs-samples-java/src/test/java/testcode/taint/StaticContextTaintPropagation.java
Fixing #541 - RuntimeException when processing static method
Thanks.
> 541  RuntimeException when processing static method

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
> SCRIPT_ENGINE_INJECTION and TEMPLATE_INJECTION_VELOCITY: typo/grammar fix

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetector.java
- findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetectorTest.java
- findsecbugs-samples-java/src/test/java/testcode/password/UnsafeCompareHash.java
- website/BuildWebPage.groovy
> Add exception for the keyword share #558

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/serial/ObjectDeserializationDetector.java
- findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/serial/ObjectDeserializationDetectorTest.java
> Add support for ObjectInput.readObject() for deserialization vuln #563

- cli/findsecbugs.sh
Change --version-list to -V to support busybox version of the sort command #570
> Change --version-list to -V

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ImproperHandlingUnicodeDetector.java
- findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/ImproperHandlingUnicodeDetectorTest.java
- findsecbugs-samples-java/src/test/java/testcode/unicode/RiskyCaseMappingSample.java
- findsecbugs-samples-java/src/test/java/testcode/unicode/RiskyNormalizationSample.java
Attempt to reduce potential false positive for #577
> Attempt to reduce potential false positive #577

- .github/workflows/spotbugs.yml
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/crypto/StaticIvDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ldap/LdapEntryPoisoningDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/IntuitiveHardcodePasswordDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/JschPasswordDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/CorsRegistryCORSDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflowEngine.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/wicket/WicketXssComponentDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssJspDetector.java
First pass of SpotBugs fixes.
This is the first time that bug are fixes by looking at the annotations produced by GH action. (Used to be tested manually on IntelliJ)
> Minor documentation and fixes

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
Add a simple solution to LDAP Injection and updated the references.
> Add solution to LDAP Injection

- .travis.yml
- pom.xml
> Attempt to export JaCoCo coverage file #608

- .travis.yml
- findsecbugs-plugin/src/main/resources/metadata/messages.xml
- Fix solution for XXE with TransformerFactory #638
- Introduce a bonus change from @Taher-Ghaleb
> Fix solution for XXE with TransformerFactory

- website/BuildWebPage.groovy
- website/templates/bugs.htm
- website/templates/home.htm
- website/templates/social.htm
- Update data in script generation.
- Update script for website generation to generate link opening on new window.
- Deprecated Google Plus
> Update data in script generator

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ReDosDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/RedosAnnotationDetector.java
- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/RegexRedosAnalyzer.java
- findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
- findsecbugs-plugin/src/main/resources/metadata/messages.xml
- findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/ReDosDetectorTest.java
- findsecbugs-samples-deps/src/main/java/javax/validation/constraints/Pattern.java
- findsecbugs-samples-java/src/test/java/testcode/Pattern.java
- findsecbugs-samples-java/src/test/java/testcode/RedosInPatternAnnotation.java
ReDOS detection for the Pattern annotation
Regex analysis was extracted for better reuse
> ReDOS detection for the Pattern annotation #426

- cli/gradle.properties
- pom.xml
This should bring compatibility to JDK 21 (see #723)
> Upgrade SpotBugs to 4.8.3

- findsecbugs-plugin/pom.xml
- findsecbugs-samples-deps/pom.xml
- findsecbugs-samples-java/pom.xml
- findsecbugs-samples-java11/pom.xml
- findsecbugs-samples-jsp/pom.xml
- findsecbugs-samples-kotlin/pom.xml
- findsecbugs-test-util/pom.xml
- pom.xml
Include the exact state that was released.
> Release 1.13.0

- findsecbugs-plugin/src/main/resources/metadata/messages.xml
Small typo and grammatical fixes in `messages.xml`.
> Fix typos in `messages.xml`

- findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/BCELUtil.java
Trying to fix #595. "Trying" because we have no concurrent tests and tests that would include GC.
The idea is to synchronize the static cache operations but still detect when objects are taken by GC. 
Using SoftReference ... (https://www.baeldung.com/java-reference-types) on the values, keeping keys in the memory.
This is a trade off between the CPU and memory since keys will be held but computed values can be freed by GC when near OOME.
This implementation doesn't take into account the "IDE use" from https://github.com/find-sec-bugs/find-sec-bugs/issues/595#issuecomment-802953956. When the underlying class is recompiled and parent interfaces are changed. In such case the static cache might return old results that are no longer valid, especially if IDE loads FindSecurityBugs into IDE's …
> Use SoftRerefence to detect if the value was already taken by GC (#595)

- website/BuildWebPage.groovy
> Updated latest version in the website
