find-sec-bugs/find-sec-bugs

plugin/src/main/java/com/h3xstream/findsecbugs/crypto/CipherWithNoIntegrityDetector.java
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/CipherWithNoIntegrityDetectorTest.java
plugin/src/test/java/testcode/crypto/CipherNoIntegrity.java

I think bugs should be reported for default cipher instances (without specified mode) too. I have also written a test for the whole class and refactor it a bit.

ECB and no integrity detection + tests

---

findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/BaseDetectorTest.java
findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/service/ClassFileLocator.java
findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/service/FindBugsLauncher.java

- This allows to test scenarios where bugs occur due to interactions with
code from third-party libraries.
- Overrides BaseDetector.analyze() and FindbugsLauncher.analyze() to allow
adding paths to auxClassPath during tests execution.
- Add utility methods to get paths to jars in src/test/resources.

Allow analyze to set classpath entries

---

plugin/src/main/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetectorTest.java

I have created a separated bug pattern for hard coded cryptographic keys - ConstantPasswordDetector now reports hard coded passwords for String and char array types and hard coded keys for the other types. I think this is appropriate since both weaknesses have different CWE ID and are equally important.

Separated hard coded password and key reporting

---

plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummary.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/taint-config/methods-summaries.txt
plugin/src/test/java/com/h3xstream/findsecbugs/UnvalidatedRedirectDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/injection/command/CommandInjectionDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/injection/stringbuilder/InjectionWithStringBuilderTest.java
plugin/src/test/java/testcode/command/CommandInjection.java

Besides the String type, I have also excluded parameters of type java.lang.Object - these are not immutable, but cannot be modified without casting to a concrete type, so I think it is quite good approximation and better solution, then adding many methods to method-summaries.txt.

Unknown methods made to modify taint state of their parameters to unknown

---

plugin-deps/src/main/java/javax/servlet/http/HttpServletResponse.java
plugin/src/main/java/com/h3xstream/findsecbugs/HttpResponseSplittingDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/crypto/WeakMessageDigestDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/redirect/RedirectionSource.java
plugin/src/main/java/com/h3xstream/findsecbugs/jsp/JstlOutDetector.java
plugin/src/main/resources/injection-sinks/response-splitting.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/main/resources/taint-config/methods-summaries.txt
plugin/src/test/java/com/h3xstream/findsecbugs/HttpResponseSplittingDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/WeakMessageDigestDetectorTest.java
plugin/src/test/java/testcode/ResponseSplittingServlet.java
plugin/src/test/java/testcode/crypto/WeakMessageDigest.java
plugin/src/test/java/testcode/crypto/WeakMessageDigestAdditionalSig.java

Fixes #121 and fixes #120. In addition, I have modified many reported messages - injectable arguments are shown for every injection and messages should be more unified (capital letters, periods etc.), please check if there is something you don't like.

Response splitting, hash functions and messages

---

findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/service/ClassFileLocator.java

- Spaces and other chars would get encoded hen creating the URL,
this fix allows to get a decoded path that can actually map to the filesystem.

Properly handle paths to files

---

plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssJspDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssServletDetector.java

Now it detects many more bugs. But I think it would be still better not to rely on this and check presence of `response.getWriter().println()` directly.

Analysis of indirect subclasses of HttpServlet for XSS

---

plugin-deps/src/main/java/org/owasp/esapi/Encoder.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/SinksLoader.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintAnalysis.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummary.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummaryMap.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodSummaryMapLoader.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintSink.java
plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssJspDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/xss/XssServletDetector.java
plugin/src/main/resources/safe-encoders/xss-encoders.txt
plugin/src/main/resources/taint-config/other.txt
plugin/src/test/java/com/h3xstream/findsecbugs/injection/SinkFilesValidationTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/jsp/JspXssDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/MethodSummaryValidationTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/xss/XssServletDetectorTest.java
plugin/src/test/java/testcode/xss/servlets/XssServlet3.java

First version of sanitization support - methods can be configured to add or remove tags for method output and detectors can read them to decide whether to report the bug. Currently, only XSS_SAFE tag is supported, but I'm going to add more before the new release.
Sanitized values for XSS are reported with low priority (less than for inputs with unknown taint state). I don't want to exclude those detections completely, because configured escape methods are context specific and there is still a risk of a successful XSS if an inappropriate sanitization method is chosen.

Taint tags - support for taint sanitization (strating with XSS)

---

plugin/src/main/java/com/h3xstream/findsecbugs/injection/custom/CustomInjectionSource.java

http://h3xstream.github.io/find-sec-bugs/bugs.htm#CUSTOM_INJECTION redirects to http://find-sec-bugs.github.io/bugs.htm and not to http://find-sec-bugs.github.io/bugs.htm#CUSTOM_INJECTION.   Since this is part of the find-sec-bugs site now, it makes more sense to directly use the find-sec-bugs.github.io URL.

Fix URL shown for CUSTOM_INJECTION bug warning

---

plugin/src/main/java/com/h3xstream/findsecbugs/StrutsValidatorFormDetector.java

False Positive for SECSFV: STRUTS_FORM_VALIDATION: Struts Form without input validation 
A DynaValidatorForm doesn't extend from ValidatorForm but still has a validate method.

Add Struts DynaValidatorForm support in addition to ValidatorForm

---

plugin/src/main/resources/metadata/messages_ja.xml

Here are some minor fixes to the japanese messages. These corrections are mostly related to encoding of HTML tags in  <Details> section.

Correct japanese messages formatting

---

plugin/src/main/java/com/h3xstream/findsecbugs/cookie/CookieFlagsDetector.java
plugin/src/test/java/com/h3xstream/findsecbugs/cookie/CookieFlagsDetectorTest.java
plugin/src/test/java/testcode/cookie/HttpOnlyCookieSamples.java
plugin/src/test/java/testcode/cookie/InsecureCookieSamples.java

I changed the behavior of the CookieFlagsDetector and it now covers the example found in bug #182 .
It now behaves as a "mini taint detector", some of the default Find-Bugs checks are working like this (like the SqlInjection one) and they seem to work fine.
It first finds the cookie creation call, saves the position of the cookie on the stack and checks if it can find the .setHttpOnly or setSecure method for this object on the stack.

Potential fix for issue #182 (INSECURE_COOKIE detector can be fooled by creating two or more cookies)

---

plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflowEngine.java

Environment variables with dots are hard to handle in unix shells (e.g. bash). A quick google search for 'environment variables dots' shows that many people struggle with such variables, e.g.:
http://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it
http://askubuntu.com/questions/65638/how-to-set-env-with-a-dot
http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names
To make custom configurations easier on unix systems, this PR makes find-sec-bugs also accept environment variables spelled with underscores (`_`) instead of dots (`.`). E.g. `findsecbugs_taint_customconfigfile` instead of `findsecbugs.taint.customconfigfile`. Using environment variables (rather than system properties) for configuration is e.g. helpful when …

Accept environment variables spelled with underscores

---

plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/custom/CustomInjectionDetector.java

Hi Philippe,
I applied the changes you asked for in https://github.com/find-sec-bugs/find-sec-bugs/pull/214/files/0498c65ec4d6ad7d551e3eda3120decfa82acd41#r75541057
There is one change, `loadFromSystem()` method cannot be private, it's used from https://github.com/find-sec-bugs/find-sec-bugs/blob/b073915c78b692e9d2384d25f884ea035d77e894/plugin/src/main/java/com/h3xstream/findsecbugs/injection/custom/CustomInjectionDetector.java#L74-L74 So I made it at least non-static.
Thank you.

Custom config file method refactoring

---

plugin-deps/src/main/java/android/content/LocalBroadcastManager.java
plugin-deps/src/main/java/android/support/v4/content/LocalBroadcastManager.java
plugin/src/main/java/com/h3xstream/findsecbugs/android/BroadcastDetector.java
plugin/src/test/java/com/h3xstream/findsecbugs/android/BroadcastDetectorTest.java
plugin/src/test/java/testcode/android/BroadcastIntentActivity.java
plugin/src/test/java/testcode/android/CustomLocalBroadcastManager.java

I added a check in the BroadcastDetector to validate that the sendBroadcast call is not executed on the LocalBroadcastManager class. This should fix issue #224 .
Right now it could be fooled if someone calls its Activity LocalBroadcastManager and uses the global sendBroadcast method. I could change the check for something stricter like !"android/support/v4/content/LocalBroadcastManager".equals(getClassConstantOperand()) but this would have to be changed often since it contains the API version.

Issue #224 - Added an exception for the LocalBroadcastManager in the detector.

---

plugin/src/main/java/com/h3xstream/findsecbugs/crypto/UnencryptedServerSocketDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/UnencryptedServerSocketDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/UnencryptedSocketDetectorTest.java
plugin/src/test/java/testcode/crypto/UnencryptedServerSocket.java

I added support for detecting the use of plain java.net.ServerSocket instances, similar to the one already in place for java.net.Socket, and suggesting the use of SSL server sockets (through SSLServerSocketFactory). 
The new UNENCRYPTED_SERVER_SOCKET vulnerability was relatively straightforward to integrate, it is similar to the one for UNENCRYPTED_SOCKET.
Please check if this is correct and can be integrated. The tests are passing, including the new one for UNENCRYPTED_SERVER_SOCKET.  (I just did not update the Japanese translation metadata). 
Best,
Eduardo Marques

UNENCRYPTED_SERVER_SOCKET: use of java.net.ServerSocket

---

plugin-deps/src/main/java/org/springframework/web/bind/annotation/DeleteMapping.java
plugin-deps/src/main/java/org/springframework/web/bind/annotation/GetMapping.java
plugin-deps/src/main/java/org/springframework/web/bind/annotation/PatchMapping.java
plugin-deps/src/main/java/org/springframework/web/bind/annotation/PostMapping.java
plugin-deps/src/main/java/org/springframework/web/bind/annotation/PutMapping.java
plugin/src/main/java/com/h3xstream/findsecbugs/endpoint/SpringMvcEndpointDetector.java
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/endpoint/SpringMvcEndpointDetectorTest.java
plugin/src/test/java/testcode/SpringTestController.java

Spring 4.3 introduced new annotation shortcuts for `@RequestMapping`.
For instance, `@GetMapping` is a composed annotation that acts as a shortcut for `@RequestMapping(method = RequestMethod.GET)`.
The full list of new shortcut annotations is:
* `@GetMapping`
* `@PostMapping`
* `@PutMapping`
* `@DeleteMapping`
* `@PatchMapping`
This pull request improves `SpringMvcEndpointDetector` by detecting these new annotations.
Some remarks regarding this pull request:
* I modified the English message, but I don't have the necessary skills to modify the corresponding Japanese one.
* Instead of having a hardcoded list of annotations, a more future-proof solutions would be to rely on the annotations hierarchy. Indeed, `@GetMapping` is annotated with `@RequestMapping`, `@RequestMapping` is annotated …

Improve SpringMvcEndpointDetector by detecting new RequestMapping annotation shortcuts

---

findbugs-test-util/pom.xml
plugin/pom.xml
plugin/src/main/java/com/h3xstream/findsecbugs/scala/SslDisablerDetector.java
pom.xml

Running `mvn compile` shows 3 Maven warnings which can be easily fixed.
---
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.h3xstream.findsecbugs:findsecbugs-root-pom:pom:1.6.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 86, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
This warning is about the JavaDoc plugin which doesn't have a version specified.
--> I specified the latest version (2.10.4).
---
```
[WARNING] The artifact …
```

Fix Maven warnings (missing plugin version, relocation, proprietary API)

---

plugin/src/main/java/com/h3xstream/findsecbugs/PermissiveCORSDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/PermissiveCORSDetectorTest.java
plugin/src/test/java/testcode/PermissiveCORS.java

Detector reports overly permissive CORS policy that sets asterisk as the value of the Access-Control-Allow-Origin header, like in the following examples:
response.addHeader("Access-Control-Allow-Origin", "\*");
response.setHeader("Access-Control-Allow-Origin", "\*");

Adding overly permissive CORS policy detector

---

plugin/src/main/java/com/h3xstream/findsecbugs/AnonymousLdapDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/AnonymousLdapDetectorTest.java
plugin/src/test/java/testcode/AnonymousLdap.java

The proposed detector is reporting LDAP authentication method set to "none", like so:
`env.put(Context.SECURITY_AUTHENTICATION, "none");`
`DirContext ctx = new InitialDirContext(env);`

Anonymous LDAP Bind detector

---

plugin-deps/src/main/java/javax/servlet/http/HttpServletRequest.java
plugin-deps/src/main/java/javax/servlet/http/HttpServletRequestWrapper.java
plugin-deps/src/main/java/javax/servlet/http/HttpServletResponse.java
plugin/src/main/java/com/h3xstream/findsecbugs/cookie/UrlRewritingDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/cookie/UrlRewritingDetectorTest.java
plugin/src/test/java/testcode/cookie/UrlRewriting.java

Proposed detector reports URL rewriting methods. These methods determine whether the session ID needs to be included in the URL.

Add Url rewriting detector

---

plugin/src/main/java/com/h3xstream/findsecbugs/crypto/WeakMessageDigestDetector.java
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/WeakMessageDigestDetectorTest.java
plugin/src/test/java/testcode/crypto/WeakMessageDigest.java
plugin/src/test/java/testcode/crypto/WeakMessageDigestAdditionalSig.java

Fixing WeakMessageDigestDetector not verifying one of the possible sha1 algorithm names:
`MessageDigest.getInstance("SHA");`

Fix false negative SHA in WeakMessageDigestDetector

---

plugin/src/main/java/com/h3xstream/findsecbugs/crypto/InsufficientKeySizeRsaDetector.java
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/InsufficientKeySizeRsaDetectorTest.java
plugin/src/test/java/testcode/crypto/InsufficientKeySizeRsa.java

1. Key length check up from 1024 to 2048 according to current standards and reflecting the existing bug description from messages.xml. Priority for key length between 1024 and 2048 set to low as opposed to normal for below 1024
2. Fixed the logic allowing for only one bug instance to be reported per file, now reporting all bug instances.

Fix false negatives in InsufficientKeySizeRsaDetector

---

plugin-deps/src/main/java/org/apache/commons/mail/Email.java
plugin-deps/src/main/java/org/apache/commons/mail/HtmlEmail.java
plugin-deps/src/main/java/org/apache/commons/mail/ImageHtmlEmail.java
plugin-deps/src/main/java/org/apache/commons/mail/MultiPartEmail.java
plugin-deps/src/main/java/org/apache/commons/mail/SimpleEmail.java
plugin/src/main/java/com/h3xstream/findsecbugs/crypto/InsecureSmtpSslDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/crypto/InsecureSmtpSslDetectorTest.java
plugin/src/test/java/testcode/crypto/InsecureSmtpSsl.java

Proposed detector reports SMTP SSL connections that don't verify the server certificate by default. This is equivalent to trusting all certificates. Affected APIs:
org.apache.commons.mail.Email
org.apache.commons.mail.HtmlEmail
org.apache.commons.mail.ImageHtmlEmail
org.apache.commons.mail.MultiPartEmail
A bug instance would be reported if the sslCheckServerIdentity property wasn't properly set in the below example:
`imageEmail.setSSLOnConnect(true);`
`imageEmail.setSSLCheckServerIdentity(true); //OK`

Add Insecure SMTP SSL detector

---

plugin-deps/src/main/java/com/amazonaws/auth/BasicAWSCredentials.java
plugin-deps/src/main/java/com/amazonaws/services/simpledb/AmazonSimpleDBClient.java
plugin-deps/src/main/java/com/amazonaws/services/simpledb/model/SelectRequest.java
plugin-deps/src/main/java/com/amazonaws/services/simpledb/model/SelectResult.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/aws/AwsQueryInjectionDetector.java
plugin/src/main/resources/injection-sinks/aws.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/injection/aws/AwsQueryInjectionDetectorTest.java
plugin/src/test/java/testcode/AwsQueryInjection.java

Proposed detector reports AWS Query Injection which is analogical to SQL Injection (with the limitations of the AWS SimpleDB Select operation). Simplified concept below:
```java
AmazonSimpleDBClient sdbc = new AmazonSimpleDBClient(appAWSCredentials);
String productCategory = request.getParameter("productCategory");
String query = "select * from invoices where productCategory = '"
+ productCategory + "' and customerID = '"
+ customerID + "' order by '"
+ sortColumn + "' asc";
SelectResult sdbResult = sdbc.select(new SelectRequest(query));
```

Add AWS Query Injection detector

---

plugin-deps/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
plugin-deps/src/main/java/org/springframework/security/config/annotation/web/configuration/EnableWebSecurity.java
plugin-deps/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java
plugin-deps/src/main/java/org/springframework/security/config/annotation/web/configurers/AbstractHttpConfigurer.java
plugin-deps/src/main/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java
plugin-deps/src/main/java/org/springframework/web/bind/annotation/RequestMethod.java
plugin/src/main/java/com/h3xstream/findsecbugs/csrf/SpringCsrfProtectionDisabledDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/csrf/SpringCsrfUnrestrictedRequestMappingDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/csrf/SpringCsrfProtectionDisabledDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/csrf/SpringCsrfUnrestrictedRequestMappingDetectorTest.java
plugin/src/test/java/testcode/csrf/SafeSpringCsrfRequestMappingController.java
plugin/src/test/java/testcode/csrf/SpringCsrfProtectionDisabled.java
plugin/src/test/java/testcode/csrf/UnsafeSpringCsrfRequestMappingController.java

This pull request includes 2 related detectors, each in a separated commit.
Recent versions of Spring Security protect *by default* Spring endpoints against CSRF attacks.
Since it does require some initial work from the developers on the client-side to make form submissions and/or AJAX requests work, it can be tempting to disable the CSRF protection temporarily in an initial development phase, with the risk of forgetting to re-enable it later on.
This detector detects the deactivation of Spring Security's CSRF protection via Spring JavaConfig.
It does not however detects the deactivation of CSRF protection via Spring XML config.
Although it can be customized, out of the box Spring Security *doesn't* protect endpoints with the HTTP request methods `GET`, `HEAD`, `TRACE`, and `OPTIONS` …

Spring CSRF: Protection Disabled & Unrestricted RequestMapping

---

.travis.yml

Some improvements to the Travis build:
* Use Maven batch mode to avoid showing download progress in the logs (`3/20 KB... 9/20 KB... 18/20 KB...`) and to ensures that the build won't hang due to waiting for user input. [Travis uses this by default](https://docs.travis-ci.com/user/languages/java/#Projects-Using-Maven) and it's [recommended by Sonatype](http://blog.sonatype.com/2009/01/maven-continuous-integration-best-practices/).
* Use the Maven phase `verify` instead of the phase `test`, which is further in the [phases lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html). This will make Travis check for the licenses headers, as the [license:check goal is attached to the verify phase by default](http://code.mycila.com/license-maven-plugin/#goals).

Travis improvements: batch mode and verify phase

---

plugin-deps/src/main/java/org/apache/commons/beanutils/BeanUtils.java
plugin-deps/src/main/java/org/apache/commons/beanutils/BeanUtilsBean.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/beans/BeanInjectionDetector.java
plugin/src/main/resources/injection-sinks/beans.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/injection/beans/BeanInjectionDetectorTest.java
plugin/src/test/java/testcode/BeanInjection.java

There are JavaBeans population methods designed for converting HTTP request parameters into a set of corresponding property setter calls on an arbitrary JavaBean. More info here:
https://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.2/apidocs/org/apache/commons/beanutils/package-summary.html#conversion.beanutils
An attacker can leverage this functionality to access special bean properties like class.classLoader that will allow him to override system properties and potentially execute arbitrary code. Below is an example of a vulnerable code:
```java
MyBean bean = ...;
HashMap map = new HashMap();
Enumeration names = request.getParameterNames();
while (names.hasMoreElements()) {
String name = (String) names.nextElement();
map.put(name, request.getParameterValues(name));
} …
```

Add JavaBeans Property Injection detector

---

plugin/pom.xml
pom.xml

The sources of the module "findsecbugs-plugin" are using some Java 7 APIs (e.g. `Objects#requireNonNull`, `Objects#equals`, `Objects#hash`). We could easily get rid of them to maintain compatibility with Java 6. However, FindBugs 3.0.1 requires Java 7, and fb-contrib 6.8.2 requires FindBugs 3.0.1, so moving the minimum required version to Java 7 probably makes sense.
Even though the plugin itself is compatible with Java 7, the project needs to be built with Java 8, as the *test* sources of the module "findsecbugs-plugin" are using some new Java 8 APIs (e.g. `String#join`, `Statement#executeLargeUpdate`, `java.util.function.Supplier`).
This introduces the risk that the *sources* of the module "findsecbugs-plugin" might end up using some Java 8 APIs by inadvertence. As documented in the …

Java source and target from 1.6 to 1.7 & API compatibility check

---

plugin-deps/src/main/java/org/apache/struts/action/ActionForward.java
plugin-deps/src/main/java/org/springframework/web/servlet/ModelAndView.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/fileDisclosure/FileDisclosureDetector.java
plugin/src/main/resources/injection-sinks/spring-file-disclosure.txt
plugin/src/main/resources/injection-sinks/struts-file-disclosure.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/injection/fileDisclosure/FileDisclosureDetectorTest.java
plugin/src/test/java/testcode/FileDisclosure.java

Proposed detector reports code utilizing ActionForward (Struts) or ModelAndView (Spring) to construct a server-side redirect path with user input. This may allow an attacker to view sensitive files or download application binaries.
Vulnerable code sample:
```java
... 
String returnURL = request.getParameter("returnURL");
return new ModelAndView(returnURL); 
```
or
```java
... 
String returnURL = request.getParameter("returnURL"); 
Return new ActionForward(returnURL);
```

Add File Disclosure Injection detector

---

plugin/src/main/java/com/h3xstream/findsecbugs/injection/formatter/FormatStringManipulationDetector.java
plugin/src/main/resources/injection-sinks/formatter.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/injection/formatter/FormatStringManipulationDetectorTest.java
plugin/src/test/java/testcode/FormatStringManipulation.java

Proposed detector reports format string argument allowing user controlled parameters like so:
```java
...
+String format = "The customer: %s %s has the balance %4$." + userInput + "f";
+formatter.format(format, firstName, lastName, accountNo, balance);
```
Allowing user input to control format parameters could enable an attacker to leak information or cause exceptions to be thrown which could lead to application failure.
Affected APIs:
java/util/Formatter.format
java/io/PrintStream.printf
java/io/PrintStream.format
java/lang/String.format

Add Format String Manipulation Injection Detector

---

plugin-deps/src/main/java/org/apache/commons/httpclient/methods/GetMethod.java
plugin-deps/src/main/java/org/apache/http/client/methods/HttpGet.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/http/HttpParameterPollutionDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
plugin/src/main/resources/injection-sinks/http-parameter-pollution.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/main/resources/safe-encoders/other.txt
plugin/src/main/resources/safe-encoders/owasp.txt
plugin/src/test/java/com/h3xstream/findsecbugs/injection/http/HttpParameterPollutionDetectorTest.java
plugin/src/test/java/testcode/HttpParameterPollution.java

Proposed detector reports HTTP Parameter Pollution (HPP), an attack that consist of injecting query string delimiters into other existing parameters. If a web application does not properly sanitize user input, a malicious user may compromise the logic of the application..
In the following example the attacker could provide a lang such as en&user_id=1, which would enable him to change the user_id at will.
```java
String lang = request.getParameter("lang");
+GetMethod get = new GetMethod("http://www.host.com");
+get.setQueryString("lang=" + lang + "&user_id=" + user_id);
+get.execute();
```

Add HTTP Parameter Pollution Injection Detector

---

plugin/src/main/java/com/h3xstream/findsecbugs/spring/SpringUnvalidatedRedirectDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/spring/SpringUnvalidatedRedirectDetectorTest.java
plugin/src/test/java/testcode/spring/SpringUnvalidatedRedirectController.java

This adds a detector for unvalidated redirects in Spring MVC web applications.  The detector looks for a view prefix of "redirect:", which instructs the controller to perform a redirect to a specified URL.  The detector only looks at classes with "RequestMapping" annotations.  This should limit inspection to controllers and abstract classes that define endpoints.

Spring Unvalidated Redirect Detector

---

plugin/src/main/resources/metadata/messages.xml

Hey,
just noticed a typo in the documentation. Would be happy if this is merged.
Cheers,
Christoph

Fix typo in documentation

---

plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintClassConfig.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodConfig.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodConfigWithArgumentsAndLocation.java

Hi @h3xstream,
a small bug fix. 
I encountered valid method name prefixed with underscore but we don't accept it, because the regexp was too specific.
Thanks.

Validate taint config class and method names as java identifiers

---

plugin-deps/src/main/java/javax/servlet/RequestDispatcher.java
plugin-deps/src/main/java/javax/servlet/ServletContext.java
plugin-deps/src/main/java/javax/servlet/ServletRequest.java
plugin-deps/src/main/java/javax/servlet/ServletRequestWrapper.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/fileDisclosure/FileDisclosureDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/scala/SSRFDetector.java
plugin/src/main/resources/injection-sinks/requestdispatcher-file-disclosure.txt
plugin/src/main/resources/injection-sinks/urlconnection-ssrf.txt
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/main/resources/taint-config/java-ee.txt
plugin/src/test/java/com/h3xstream/findsecbugs/injection/fileDisclosure/FileDisclosureDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/scala/SSRFDetectorTest.java
plugin/src/test/java/testcode/FileDisclosure.java
plugin/src/test/java/testcode/UrlConnectionSSRF.java

Hi @h3xstream,
I extended detectors for vulnerabilities I met recently.
I reused `scala.SSRFDetector` class for the SSRF check even though it's not scala. I'm not sure if you would like to split it into 2 separate detectors - one for Scala and one for Java, or extract the `SSRFDetector` out of `scala` package and have just one class for both.
Thanks.

SSRF and LFI using RequestDispatcher and URLConnection

---

plugin/src/test/java/com/h3xstream/findsecbugs/injection/custom/CustomInjectionDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/xss/JspXssDetectorTest.java
plugin/src/test/resources/com/h3xstream/findsecbugs/xss/CustomConfig.txt
plugin/src/test/webapp/xss/xss_8_request_attribute.jsp

Hi @h3xstream,
test for `TaintMethodConfigWithArgumentsAndLocation` with examples (https://github.com/find-sec-bugs/find-sec-bugs/pull/330#issuecomment-323161835)
I hope it improves the coverage.
I also fixed an unrelated bug in `CustomInjectionDetectorTest`. Beside the configuration reset I had to move the code into `@After/BeforeClass`, with `@After/BeforeTest` it didn't work, I'm not sure why.
Thanks.

Test for TaintMethodConfigWithArgumentsAndLocation with examples

---

plugin/pom.xml
pom.xml

part I : enabling assertions during testing

Enable assertions during building and/or using find-sec-bugs #338

---

plugin/src/main/java/com/h3xstream/findsecbugs/common/StackUtils.java
plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/password/HardcodedPasswordEqualsDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/password/IntuitiveHardcodePasswordDetector.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/InvalidStateException.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintAnalysis.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflowEngine.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameAdditionalVisitor.java
plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/password/HardcodedPasswordEqualsDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetectorTest.java
plugin/src/test/java/testcode/password/EqualsPasswordField.java
plugin/src/test/java/testcode/password/UnsafeCompareHash.java

New detector for hardcode password but also new API for custom dataflow tagging beyond injection based bug patterns.
@formanek If you have some time, you could look at this new API and give me your toughs.
- Detectors register to be able to intercept dataflow events : https://github.com/find-sec-bugs/find-sec-bugs/pull/343/commits/bccb39c1e758a72624bb87a1b7940369c086a6d2#diff-380c845ae06beefe8f07d853659ce8c0R60
- Model Visitor call detector's `TaintFrameAdditionalVisitor` after the instruction was process with the normal logic https://github.com/find-sec-bugs/find-sec-bugs/pull/343/commits/bccb39c1e758a72624bb87a1b7940369c086a6d2#diff-c1d98326cbc7a19685ad97d009b12372R272
- Visitors can additional tag  https://github.com/find-sec-bugs/find-sec-bugs/pull/343/commits/bccb39c1e758a72624bb87a1b …

Detect hardcode password and hash based on variable name

---

website/templates/bugs.htm

Two fixes in one (sorry, I would create two PRs, but they'd just conflict):
#345 add the "bug pattern" to the bugs documentation page, as people will likely be searching for these strings (since they appear in the findbugs output)
#160 add a table of contents to bugs page

Improvement to bug descriptions (Public Website)

---

plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
plugin/src/main/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetector.java
plugin/src/main/resources/metadata/findbugs.xml
plugin/src/main/resources/metadata/messages.xml
plugin/src/test/java/com/h3xstream/findsecbugs/xml/TransformerFactoryDetectorTest.java
plugin/src/test/java/com/h3xstream/findsecbugs/xml/XxeDetectorTest.java
plugin/src/test/java/testcode/xxe/transformerfactory/TransformerFactorySafe.java
plugin/src/test/java/testcode/xxe/transformerfactory/TransformerFactoryVulnerable.java
plugin/src/test/java/testcode/xxe/xmlinputfactory/XmlInputFactorySafe.java
plugin/src/test/resources/testcode/xxe/dos_xxe.xml
plugin/src/test/resources/testcode/xxe/simple_xxe.xslt

I have created a detector to add some XXE coverage (related to issue #138).
This detector detects the use of the TransformerFactory class without the `FEATURE_SECURE_PROCESSING`, `ACCESS_EXTERNAL_DTD` or `ACCESS_EXTERNAL_STYLESHEET` flags.
I have noted during my tests that even if these flags are set, the TransformerFactory class is still vulnerable to Denial of Service attacks (like LoL Bombs). However, I have not found a way to completely remove entity processing in the classic TransformerFactory.
I have also discovered during my tests that the `XmlInputFactorySafe.parseXMLSafe2` method could also be vulnerable to XXE Denial or Service attacks. Maybe this should not be considered "safe" but should instead flag a lower severity vulnerability.

Added some XXE Coverage for TransformerFactory

---

plugin/src/main/resources/taint-config/java-ee.txt
plugin/src/test/java/com/h3xstream/findsecbugs/xss/XssServletDetectorTest.java
plugin/src/test/java/testcode/xss/servlets/XssServlet7.java

As @h3xstream suggested on the issue #358, I added a source in the java-ee.txt file and create test cases.
Could you review the pull request?
Thank you
- Add source FileItem.getName() on the java-ee.txt
- Create test code class named XssServlet7.java
- Add corressponding test driver detectXssServlet7() on the XssServletDetectorTest.java

FileItem.getName() as a new source for XSS_SERVLET

---

plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/BaseConfigValidation.java
pom.xml

At some point oracle JDK was simply not available on Travis-CI.
Now, I realise that it is running but some test are failing because of class removed/deprecated in Java 9.

Make Java 9 build mandatory for Travis-CI

---

.travis.yml

oraclejdk10 was changed to openjdk10 based on a recent error message on Travis-CI.
```
oraclejdk10 is deprecated. See https://www.oracle.com/technetwork/java/javase/eol-135779.html for more details. Consider using openjdk10 instead.
```

Fix TravisCI for JDK version 10

---

cli/findsecbugs.sh

- Decouple the launcher from the find-sec-bugs version
- Made it runnable from any directory
- Fix a bug with certain JDK classloaders not able to load wildcards
jars.
**This work has been sponsored by Doyensec LLC** [![Doyensec](https://www.doyensec.com/images/logo.svg)](https://doyensec.com/)

Improve and generalize the CLI unix launcher

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/CorsRegistryCORSDetector.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/PermissiveCORSDetectorTest.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/spring/CorsRegistryCORSDetectorTest.java
findsecbugs-samples-deps/src/main/java/org/springframework/web/servlet/config/annotation/CorsRegistration.java
findsecbugs-samples-deps/src/main/java/org/springframework/web/servlet/config/annotation/CorsRegistry.java
findsecbugs-samples-deps/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurer.java
findsecbugs-samples-java/src/test/java/testcode/cors/PermissiveCORS.java
findsecbugs-samples-java/src/test/java/testcode/cors/SpringPermissiveCORSInsecure.java
findsecbugs-samples-java/src/test/java/testcode/cors/SpringPermissiveCORSSecure.java

Springboot developer may use CorsRegistration to set access-control-allow-origin to `*`, which is permissive. The vulnerable code may like this:
```java
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {
@Override
public void addCorsMappings(CorsRegistry registry) {
registry.addMapping("/**")
.allowedOrigins("*") //vulnerable
.allowedMethods("GET","POST","PUT", "DELETE")
.allowCredentials(true).maxAge(3600);
}
}
```
This detector can find this pattern.

Add  permissive CORS detector for CorsRegistration in Springboot

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java

Hi @h3xstream,
I didn't add any test because we don't have any for taint analysis itself :(
I reproduced it when analyzing https://github.com/liferay/liferay-portal/blob/8362adb202e75dbf328b90abb4a9782b13457a21/modules/apps/document-library/document-library-document-conversion/src/main/java/com/liferay/document/library/document/conversion/internal/DocumentConversionImpl.java#L81 with `com/liferay/document/library/document/conversion/internal/DocumentConversionImpl._validate(Ljava/lang/String;Ljava/lang/String;)V:0,1|+PATH_TRAVERSAL_SAFE#0,1` whitelist.
Then it failed here: 
https://github.com/find-sec-bugs/find-sec-bugs/blob/8b32373515e627cc42704b9e3edb5508c6ddb2bf/findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java#L329

local-variable-index-rewrite-bug

---

findbugs-test-util/src/test/java/com/h3xstream/findbugs/test/matcher/BugInstanceMatcher.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/BCELUtil.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/AbstractInjectionDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/AbstractTaintDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/ClassMethodSignature.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/InjectionSink.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/MethodAndSink.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/redirect/UnvalidatedRedirectDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintAnalysis.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintClassConfig.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintConfig.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintDataflowEngine.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFieldConfig.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodConfig.java
findsecbugs-plugin/src/main/resources/taint-config/collections.txt
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/ParameterTaintBackPropagationTest.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/StaticContextTaintPropagationTest.java
findsecbugs-plugin/src/test/resources/com/h3xstream/findsecbugs/taintanalysis/CustomConfig.txt
findsecbugs-samples-java/src/test/java/testcode/taint/ParameterTaintBackPropagation.java
findsecbugs-samples-java/src/test/java/testcode/taint/StaticContextTaintPropagation.java

Hi @h3xstream,
these are some improvements I made in April when analyzed the Liferay portal. I didn't get to make it prettier and don't want to block it on my side anymore.
I'd like to ask you to go together through the changes, discuss them, improve them and hopefully merge them.
I tested the code when working with the plugin but it's possible I introduced some inconsistencies/bugs so I'd be glad for a review.
Thank you.
The important things:
1, Automatic back-propagation of taints from method calls. 
2, Improved static fields and static blocks analysis
3, GC improvements
**Automatic back-propagation of taints from method calls**
I realized there is lot of unknown in the interprocedural analysis. When we call a safe method `safe(Map a)` and the method doesn't change the parameter we are …

190430-taint-method-propagation-II

---

findsecbugs-plugin/src/main/resources/injection-sinks/sql-hibernate.txt

Added a sink signature for the deprecated hibernate createQuery, which returns org.hibernate.query.Query.

Unable to detect injections on older versions of Hibernate

---

.travis.yml
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/SignatureParserWithGeneric.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/SpringEntityLeakDetector.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/spring/SpringEntityLeakDetectorTest.java
findsecbugs-samples-java/pom.xml
findsecbugs-samples-java/src/test/java/testcode/pathtraversal/PathTraversalConstantValue.java
findsecbugs-samples-java/src/test/java/testcode/spring/SpringEntityLeakController.java
pom.xml
website/BuildWebPage.groovy

- Detect mass assignment with pattern like `public void updateUsers(List<User> user)`
- Separate mass assignment (incoming) and data leakage (outgoing).
- The id and title were rename to avoid mentioning Spring. Other detector could identify such a bug in other framework.
- Along with the general guidelines, a Spring MVC solution was given (taken from OWASP cheat sheet mass assigment).

Improvement to information leakage and mass assignment detection

---

findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/xml/EnabledExtensionsInApacheXmlRpcTest.java

The declared package "com.h3xstream.findsecbugs" does not match the expected package "com.h3xstream.findsecbugs.xml"

change package to "com.h3xstream.findsecbugs.xml"

---

findsecbugs-plugin/src/main/resources/safe-encoders/other.txt
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/injection/http/HttpParameterPollutionDetectorTest.java
findsecbugs-samples-deps/src/main/java/com/google/common/escape/Escaper.java
findsecbugs-samples-deps/src/main/java/com/google/common/net/PercentEscaper.java
findsecbugs-samples-deps/src/main/java/com/google/common/net/UrlEscapers.java
findsecbugs-samples-java/src/test/java/testcode/HttpParameterPollution.java

Added Google Guava's `Escaper` as a sanitizer. Updated the `HttpParameterPollution` to include a HttpGet object construction passing a escaped string using `urlPathSegmentEscaper`. Added stub classes for the Google Guava classes - `Escaper`, `PercentEscaper` and `UrlEscapers`.
#504

Supporting com/google/common/escape/Escaper as sanitizer

---

cli/build.gradle

Update SpotBugs to 3.1.12 which include ASM library compatible with Java 11. Fix #512

Update SpotBugs to 3.1.12

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/crypto/StaticIvDetector.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/crypto/StaticIvDetectorTest.java
findsecbugs-samples-java/src/test/java/testcode/crypto/iv/StaticIvUnwrap.java
findsecbugs-samples-java/src/test/java/testcode/crypto/iv/StaticIvWrap.java

Fixes #517.
This makes wrapping and unwrapping equivalent to encryption and decryption for the purposes of the `STATIC_IV` check.

Change STATIC_IV detector to properly handle key wrapping/unwrapping modes

---

findsecbugs-plugin/src/main/resources/metadata/messages.xml

This is an open discussion as the description can be also given for @Value without additional information.
It still can be vulnerable if the annotation use some SpEL voodoo but I'm not sure if how exactly.
Example of a "vulnerable" application : 
```java
public class ClientRepository {
@Value("${jdbc.query.create.client}")
private String reqCreateClient;  // INSERT INTO client (no_client, name, mail, date_inscrit) VALUES (?, ?, ?, ?);
@Autowired
private JdbcTemplate jdbcTemplate;
public int createClient(Client client) {
Assert.notNull(client, "entity cannot be null");
try {
return jdbcTemplate.update(reqCreateClient, ps -> {
Assert.notNull(client.getId(), "embedded id clientId cannot be null");
ps.setInt(1, client.getId());
ps.setString(2, client.getName());
ps.setString(3, …
```

Add example for sql_injection_spring_jdbc with annotation

---

findsecbugs-samples-java/src/test/java/testcode/serial/ObjectInputSig.java

It should fix `package com.sun.istack.internal does not exist` in OpenJDK 8 and +

Remove Nullable annotation not available in OpenJDK according to build

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/sql/SqlInjectionDetector.java
findsecbugs-plugin/src/main/resources/injection-sinks/sql-vertx-sql-client.txt
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/injection/sql/VertxSqlClientSqlDetectorTest.java
findsecbugs-samples-deps/src/main/java/io/vertx/core/AsyncResult.java
findsecbugs-samples-deps/src/main/java/io/vertx/core/Future.java
findsecbugs-samples-deps/src/main/java/io/vertx/core/Handler.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/PreparedQuery.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/PreparedStatement.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/Query.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/Row.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/RowSet.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/SqlClient.java
findsecbugs-samples-deps/src/main/java/io/vertx/sqlclient/SqlConnection.java
findsecbugs-samples-java/src/test/java/testcode/sqli/VertxSqlClient.java

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
This is a initial pull request to add a sql injection detector for vert.x sql client. The code passes the tests but the build is failing due to missing headers on the mock API.
I am wondering how could one solve the issue, as it seems that the remaining mocks do not have any headers, so I'm a bit lost here how to fix it.

Initial version of a Vert.x Sql Client detector

---

findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/bugs/WebGoatCreateDb529Test.java
findsecbugs-samples-java/src/test/java/testcode/bugs/WebGoatCreateDb529.java

First step to reproduce the case..
So far no anomaly was found.. Maybe I confused old FindBugs detector ** bug instance with the one from FSB..
```
------------------------------------------------------
New Bug Instance: [1]
message=SQL: testcode.bugs.WebGoatCreateDb529.createTransactionTable(Connection) passes a nonconstant String to an execute or addBatch method on an SQL statement
bugType=SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE  priority=Low  category=S
class=testcode.bugs.WebGoatCreateDb529  method=createTransactionTable  line=43
------------------------------------------------------
```
** SQL_NONCONSTANT_STRING_PASSED_TO_EXECUTE is very rudimentary. It does not attempt to eliminate much false positive.

Test case to reproduce #529

---

.github/workflows/spotbugs.yml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/bugs/OutOfBoundsLocalVariableIndex556Test.java
pom.xml

Based on failure from the previous yml configuration..
https://github.com/find-sec-bugs/find-sec-bugs/actions/runs/226427569
- Some changes weere made to make sure the verify phase would pass
- The Maven plugin was configure to use the version 3.1.12

A couple of fixes for Github Action

---

index.htm

The old [FindBugs-IDEA plugin](https://plugins.jetbrains.com/plugin/3847?pr=idea) doesn't work with current versions of IntelliJ.

Link to the SpotBugs plugin for IntelliJ

---

findsecbugs-plugin/src/main/resources/password-methods/password-methods-all.txt
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/password/ConstantPasswordDetectorTest.java
findsecbugs-samples-deps/src/main/java/io/vertx/core/Vertx.java
findsecbugs-samples-deps/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java
findsecbugs-samples-deps/src/main/java/io/vertx/ext/web/RoutingContext.java
findsecbugs-samples-deps/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
findsecbugs-samples-java/src/test/java/testcode/oauth/VertxOauth2Config.java
findsecbugs-samples-java/src/test/java/testcode/password/ConstantPasswords.java

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
This PR add support for identifying hardcoded password used in OAuth2 and CSRF handlers.
These checks were not detected automatically with the general password detector.

Add support for Vert.x web Oauth2 + CSRF handlers

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/ModificationAfterValidationDetector.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/ModificationAfterValidationTest.java
findsecbugs-samples-java/src/test/java/testcode/modify_validate/ModifyAfter.java
findsecbugs-samples-java/src/test/java/testcode/modify_validate/ModifyBefore.java

A string must not be modified after validation because it may allow an
attacker to bypass validation using a tricky string which becomes
malicious after the modification. For example, a program may filter out
the <script> tags from HTML input to avoid cross-site scripting (XSS) and
other vulnerabilities. If non-character code points are deleted from the
input following validation, an attacker may pass the string "<scr"+
"\uFDEF"+"ipt>" so that the validation check fails to detect the <script>
tag, but the subsequent removal of the non-character code pont creates a
<script> tag in the input.
This patch adds a detector for this bug.

Add new detector for MODIFICATION_AFTER_VALIDATION

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/NormalizationAfterValidationDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/NormalizeBeforeValidationDetector.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/NormalizeBeforeValidationTest.java
findsecbugs-samples-java/src/test/java/testcode/normalize/NormalizeAfter.java
findsecbugs-samples-java/src/test/java/testcode/normalize/NormalizeBefore.java

On untrusted input strings applications must employ input filtering and
validation mechanisms based on the strings' character data. For example,
to avoid cross-site scripting (XSS) vulnerabilities the <script> tag
must be forbidden in the input. Unicode strings must also be normalized
the same string can have many different representations. However, this
normalization must happen before validation and not after.
This patch adds a detector for this bug.

Add new detector for NORMALIZATION_AFTER_VALIDATION

---

findsecbugs-plugin/src/main/resources/injection-sinks/path-traversal-in.txt
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/file/NioPathTraversalTest.java
findsecbugs-samples-java/src/test/java/testcode/pathtraversal/NioPathTraversal.java

This adds the Paths.get(Uri) variant as a follow-up to https://github.com/find-sec-bugs/find-sec-bugs/issues/324
> From the Path instance built, it can be use to load the file using other API (File, FileInputStream, etc..).
This also brings the nio detector in parity with the scala version of the same detector(scala-path-traversal-in.txt) which handles `Uri`s

Add Paths.get(Uri) as source for Path traversal

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/DangerousPermissionCombination.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/DangerousPermissionCombinationTest.java
findsecbugs-samples-java/src/test/java/testcode/permission/ReflectPermissionNewProxyInPackage.java
findsecbugs-samples-java/src/test/java/testcode/permission/ReflectPermissionSuppressAccessChecks.java
findsecbugs-samples-java/src/test/java/testcode/permission/RuntimePermissionCreateClassLoader.java
findsecbugs-samples-java/src/test/java/testcode/permission/RuntimePermissionGetClassLoader.java

This bug is reported thenever ReflectPermission is granted on the target suppressAccessChecks or RuntimePermission on createClassLoader.
See [CEI CERT RULE ENV03-J](https://wiki.sei.cmu.edu/confluence/display/java/ENV03-J.+Do+not+grant+dangerous+combinations+of+permissions)

New detector FindDangerousPermissionCombination for new bug type DANGEROUS_PERMISSION_COMBINATION

---

findsecbugs-plugin/src/main/resources/metadata/messages.xml

`ReflectPermission("newProxyInPackage.*")` and `RuntimePermission("getClassLoader")` are the negative tests, thus they are considered safe. This  PR removes them from the documentation. This is a fix for #652.

Fix the examples in the documentation of DANGEROUS_PERMISSION_COMBINATION

---

findsecbugs-plugin/src/main/resources/metadata/messages.xml

Fix broken description.
XML tag that are cited code need to be escaped.
Result:

Fix unescape tag #661

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/SignatureParserWithGeneric.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/spring/SpringEntityLeakDetectorTest.java
findsecbugs-samples-java/src/test/java/testcode/spring/SpringEntityLeakController.java

Currently, the implementation assumes the signature will be of the format
`(Ljava/lang/Object,Ljava/lang/Object)`, using a comma `,` separator.
This is not the case for compiled classes. Compiled signatures use a
semicolon `;` as the separator as described in [JVMS 4.2](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-ParameterDescriptor).
This commit delegates the `SpotBugs'` signature parser to ensure the parser
expects the format it is to be provided & reduces the maintenance overhead here.
Ref #668

Correctly parse method signatures with generic types

---

website/templates/home.htm
website/templates/tutorials.htm

the old links pointed to deprecated or even disappeared plugins

updated links to plugins on website

---

cli/gradle.properties
findsecbugs-plugin/pom.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/ReDosDetectorTest.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/common/ByteCodeTest.java
findsecbugs-samples-kotlin/pom.xml
findsecbugs-test-util/pom.xml
findsecbugs-test-util/src/test/java/com/h3xstream/findbugs/test/BaseDetectorTest.java
findsecbugs-test-util/src/test/java/com/h3xstream/findbugs/test/matcher/BugInstanceMatcher.java
findsecbugs-test-util/src/test/java/com/h3xstream/findbugs/test/matcher/BugInstanceMatcherBuilder.java
pom.xml

Adds support for building on and analyzing on JDK17. Upgrades spot bugs to 4.5.3 (therefore upgrading ASM to the latest version).
I also had to upgrade Hamcrest and Mockito to deal with reflection based issues on later JDKs
Fixes https://github.com/find-sec-bugs/find-sec-bugs/issues/656.
I analyzed this branch with Sonatype Lift to make I haven't introduced any other issues (no new issues found): https://lift.sonatype.com/results/github.com/jlstephens89/find-sec-bugs/01FV0EF97XHCAXVFAY6E0NBCXE?tab=results

Add JDK17 support

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/spring/SignatureParserWithGeneric.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/spring/SpringEntityLeakDetectorTest.java
findsecbugs-samples-java/src/test/java/testcode/spring/SpringEntityLeakController.java

Proposed fix for https://github.com/find-sec-bugs/find-sec-bugs/issues/679
Replace regex parsing of the method signature by `edu.umd.cs.findbugs.ba.generic.GenericUtilities` to handle the case when a type in the method signature is an array.
Updated the unit test to include a case when a paramete and the return type are arrays.

fix: handle arrays in SignatureParserWithGeneric

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/xml/SchemaFactoryDetector.java
findsecbugs-plugin/src/main/resources/metadata/findbugs.xml
findsecbugs-plugin/src/main/resources/metadata/messages.xml
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/xml/SchemaFactoryDetectorTest.java
findsecbugs-samples-java/src/test/java/testcode/xxe/schema/SchemaFactorySafeAccessExternalDisabled.java
findsecbugs-samples-java/src/test/java/testcode/xxe/schema/SchemaFactorySafeFeatureSecureProcessing.java
findsecbugs-samples-java/src/test/java/testcode/xxe/schema/SchemaFactoryVulnerableExternalEntityRef.java
findsecbugs-samples-java/src/test/java/testcode/xxe/schema/SchemaFactoryVulnerableExternalSchemaLocation.java

This pull request implements a new Detector for XML External Entity processing with `javax.xml.validation.SchemaFactory` as described in issue #395.
The implementation follows the pattern of Validator XXE Detector and supports solutions that enable Secure Processing or disable access to both External Document Type Declarations and External Schemas.
The documentation provides examples of both external entity references and external schema locations, as well as examples of vulnerable code and potential solutions.

Add Detector for XXE in XML SchemaFactory

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/password/HashUnsafeEqualsDetector.java

We have a false positive on UNSAFE_HASH_EQUALS for a variable containing `cashAccount`, it is flagged because the rule looks for `sha`
This PR adds `cashAccount` to the list of safe words

fix: added "cash account" to the safe words, not a SHA password

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/InjectionSink.java

Hi,
In some cases it is useful to get all the byte code offsets find-sec-bugs aware of related to a single source code line, for example when one would like to get context to a specific location in a line.
We added a config flag that once set will skip the code that responsible for keeping only one SourceLineAnnotation per line.

Verbose source line locations report

---

findsecbugs-plugin/pom.xml
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/FindSecBugsGlobalConfig.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintConfig.java
findsecbugs-plugin/src/test/java/com/h3xstream/findsecbugs/taintanalysis/StringConcatenationTest.java
findsecbugs-samples-java11/pom.xml
findsecbugs-samples-java11/src/test/java/testcode/taint/StringConcatenation.java
pom.xml

Pull Request https://github.com/find-sec-bugs/find-sec-bugs/pull/690 adds handling of JDK > 8 string concatenation with invokedynamic and `makeConcatWithConstants`.  There are some cases it does not handle such as concat of long or double values.  This pull request address the parameter offsets affected by long and double, which take two spots on the stack.
It also fixes issues where taint on a stack object is modified when we do not want that.
In order to test this change, we need some sample classes built with a JDK > 8, and using JDK11 on the current `findsecbugs-samples-java` introduces errors in the unit tests so there is a build submodule that builds specific classes to a JDK 11 target.

Updates to handle string-building taint with invokedynamic concatenation in JDK > 8

---

findsecbugs-plugin/src/main/resources/metadata/messages.xml

As noted in #727 and https://github.com/spotbugs/sonar-findbugs/issues/983 the detector introduced in #681 declared a new bug code abbreviation but did not provide.
This is causing a crash when the detector reports a bug.
This should fix #727 and https://github.com/spotbugs/sonar-findbugs/issues/983

Added missing BugCode for SECXXEVAL abbrev

---

.github/workflows/spotbugs.yml

The build currently fails because it runs on JDK 8 but the findsecbugs-samples-java11 module requires java 11

Upgrade the build to run on JDK 11

---

.github/workflows/spotbugs.yml
cli/gradle.properties
pom.xml

The latest SpotBugs and SpotBugs maven plugin versions are [4.8.6](https://github.com/spotbugs/spotbugs/releases/tag/4.8.6) and [4.8.6.1](https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.8.6.1). This PR updates to these versions.
The SpotBugs GitHub Action seems to be stuck on an older SpotBugs version, and I couldn't find any reason for this. Please let me know if it was intentional.

Update SpotBugs version

---

findsecbugs-plugin/pom.xml

When I tried to run `mvn clean install` locally, the build failed and maven complained about `tasks` being deprecated and removed:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (ant-magic) on project findsecbugs-plugin: You are using 'tasks' which has been removed from the maven-antrun-plugin. Please use 'target' and 
refer to the >>Major Version Upgrade to version 3.0.0<< on the plugin site. -> [Help 1]
```
See https://maven.apache.org/plugins/maven-antrun-plugin/
This PR solves this issue.

Replace deprecated tasks with target in maven-antrun-plugin

---

findsecbugs-plugin/pom.xml

The PR #740 renamed ant `tasks` to maven `target` that requires `maven-antrun-plugin:3.0.0` or higher. 
My local env build fails, mvn doesn't download the latest dependency. Requiring the version manually fixes the problem.

Local build fails after #740

---

findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/common/ByteCode.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/common/InterfaceUtils.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/AbstractInjectionDetector.java
findsecbugs-plugin/src/main/java/com/h3xstream/findsecbugs/injection/BasicInjectionDetector.java

When looking up a class name, we sometimes mistake an array type for a simple classname, causing a subsequent class lookup to fail.
That failure is reported to Spotbugs, but apparently ignored internally.
Instead of ignoring this, we should try to extract the simple class type, and check this one instead.
Fixes #751

Remove array signature from classname

---

.github/workflows/spotbugs.yml

The `Java CI with SpotBugs` gha [fails](https://github.com/find-sec-bugs/find-sec-bugs/actions/runs/13926749724/job/38973199255) with the following message:
```
Error: Missing download info for actions/cache@v1
```
This is because the actions/cache v1 and v2 got [deprecated](https://github.com/actions/cache/discussions/1510) and [closed down](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down).
This PR updates the version of this cache service.
The job still fails on my fork, but at a later stage, when running the spotbugs gha. If I'm not mistaken, it's because I don't have some token set up or the appropriate permissions.

update gha actions/cache from v1 to v4

---

.github/workflows/spotbugs.yml
cli/gradle.properties
pom.xml

The latest SpotBugs and SpotBugs maven plugin versions are [4.9.3](https://github.com/spotbugs/spotbugs/releases/tag/4.9.3) and [4.9.3.0](https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.9.3.0). This PR updates to these versions.

update SpotBugs and SpotBugs maven plugin versions

---

pom.xml

Updating dependencies to the latest versions and with this getting rid of the following vulnerabilities from dependencies:
CVE-2024-47554 in Apache Commons IO 
CVE-2023-6378 in ch.qos.logback:logback-classic
CVE-2022-4065 in org.testng:testng

update dependency versions and fix dep vulnerabilities
